version: '3.8'
services:
  mern-frontend:
    build: frontend
    ports: 
      - "5173:5173"
  mern-backend:
    build: backend
    ports:
      - "5050:5050"
    networks:
      - mern-network
    restart:
      always
    environment:
      MONGO_URI: "mongodb://mern-mongo:27017" 
  mern-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local